### ISSUE TITLE
Admin Home Page

### ISSUE THREAD

**Issue by mcsor** [manoa-recipes/manoa-recipes-application#2]
Please do work for this task in a branch named issue-002.

**Comment by melviniwamoto** [comment]
Admin Home Page will be a simple page to browse the databases by:
1) Single Collections: To access/edit each data entry individually from a simple set of lists for all collections
2) Form/Multi Collections: adding/editing certain documents--like recipes--require subscription to multiple collections--like recipes, recipesingredients, ingredients, and vendorsingredients--and whether the relations are working properly can be assessed here.
3) User Control: We need a way to set users to the vendor role.  Eventually, if there's time and desire for it, adding more users to the admin role will also take place here.

The three sections will be in a Tabs react component, allowing the admin to browse all data that the role should be policing.
