### ISSUE TITLE
Build basis for "AddRecipe" Page

### ISSUE THREAD

**Issue by mcsor** [manoa-recipes/manoa-recipes-application#7]
Will be in a branch called issue-007

**Comment by melviniwamoto** [comment]
This issue will deal with implementing the basic structure of the page.
Going to implement it with a basic uniform to extract data to create new entries for the collections: Recipes and RecipesIngredients.
Another issue will deal with the submit button and the function it will use to actually manipulate the database.
A final issue might be to make it actually look good (styling).
