### ISSUE TITLE
IndividualRecipe Page

### ISSUE THREAD

**Issue by mcsor** [manoa-recipes/manoa-recipes-application#8]
Work on in a branch named issue-008

**Comment by melviniwamoto** [comment]
Implement basic design of page (Can use the sample data directly):
1) Recipes document data
2) RecipesIngredients document data (for the specific Recipes document)

Future issues:
1) Subscribe to the collections and use data from them
2) An edit button for the owner and the admin that links to some sort of EditRecipe page
